---

- name: Create Execution Dir
  file:
    path: /tmp/ora_user/
    state: directory
    owner: oracle
    mode: 7777
    
- name: run it as a list
  debug:
    msg: "{{ objects }}"
  loop: "{{ objects.split('\n') }}"
  

  

- name: Output Survey Variables to JSON
  template:
    src: ora_user.json.j2
    dest: "/tmp/ora_user/ora_user_{{ username }}.json"

    
- name: Set Json file Variable
  set_fact:
    jsonfile: "/tmp/ora_user/ora_user_{{ username }}.json"
    x_path: "/tmp/ora_user/"
    sqlfile: "/tmp/ora_user/create_user_{{ username }}.sql"
    
    

- name: Find out playbook's path
  shell: pwd
  register: playbook_path_output
- debug: var=playbook_path_output.stdout


- name: Jinja Template for Users Script
  template:
    src: ora_user.py.j2
    dest: /tmp/ora_user/ora_user.py
    mode: 7777

- name: Jinja Template for Grants Script
  template:
    src: ora_grants.py.j2
    dest: /tmp/ora_user/ora_grants.py
    mode: 7777

- name: change permissions
  file:
    path: "{{ x_path }}"
    state: directory
    owner: oracle
    mode: "7777"

- name: whoami
  command: whoami
  register: ora_user_output

- name: Generate User Script SQL
  command: /usr/bin/python /tmp/ora_user/ora_user.py





- name: Check to see if the .SQL file exists
  stat:
    path: /tmp/ora_user/create_user_{{username}}.sql
  register: filename

- name: fail if file doesn't exist
  fail: msg="The file didn't get created"
  when: filename.exists


- name: Generate Grant Script SQL
  command: /usr/bin/python /tmp/ora_user/ora_grants.py
  


- name: Template Orashell Script
  template:
    src: orashell.sh.j2
    dest: /tmp/ora_user/orashell.sh
    mode: 7777
    
- name: Execute Script + Set Env Variables
  shell: /usr/bin/bash /tmp/ora_user/orashell.sh
  become_user: oracle


- name: copying file with playbook
  copy:
    src: /tmp/ora_user/create_user_{{username}}.sql.log
    dest: /tmp/
    owner: oracle     
    mode: 7777
    remote_src: yes
