---

- name: Create Execution Dir
  file:
    path: /tmp/ora_user/
    state: directory
    owner: oracle
    mode: 0775
    become_user: oracle

- name: Output Survey Variables to JSON
  template:
    src: ora_user.json.j2
    dest: "/tmp/ora_user/ora_user{{ username }}.json"

    
- name: Set Json file Variable
  set_fact:
    jsonfile: "/tmp/ora_user/ora_user_{{ username }}.json"
    
    

- name: Find out playbook's path
  shell: pwd
  register: playbook_path_output
- debug: var=playbook_path_output.stdout


- name: Jinja Template for Users Script
  template:
    src: ora_user.py.j2
    dest: /tmp/ora_user/ora_user.py


- name: Jinja Template for Grants Script
  template:
    src: ora_grants.py.j2
    dest: /tmp/ora_user/ora_grants.py

- name: Generate User Creation SQL statements
  command: /tmp/ora_user/ora_user.py

- name: Generate User Grants SQL statements
  command: /tmp/ora_user/ora_grants.py

- name: Template Orashell Script
  template:
    src: orashell.sh.j2
    dest: /tmp/ora_user/orashell.sh
  
- name: Execute Script + Set Env Variables
  ansible.builtin.script: /tmp/ora_user/orashell.sh "create_user_{{ username }}.sql"
  become_user: oracle

- name: create a file cuz I can
  file:
    path: "/tmp/tempfile.txt"
    state: touch
