---
- name: Output Survey Variables to JSON
  template:
    src: ora_user.json.j2
    dest: {{ora_user + username + ".json"}}
    register: jsonfile

- name: Show copied file
  debug:
    msg: "{{ jsonfile.dest }}"

- name: Find out playbook's path
  shell: pwd
  register: playbook_path_output
- debug: var=playbook_path_output.stdout


- name: Jinja Template for Users Script
  template:
    src: ora_user.py.j2
    dest: ora_user.py


- name: Jinja Template for Grants Script
  template:
  src: ora_grants.py.j2
  dest: ora_grants.py

- name: Generate User Creation SQL statements
  command: ora_user.py

- name: Generate User Grants SQL statements
  command: ora_grants.py

- name: Execute Script + Set Env Variables
  template:
    src: orashell.sh.j2
    dest: orashell.sh
  ansible.builtin.script: orashell.sh "{{ "create_user_" + username + ".sql" }}"
  become_user: oracle

- name: create a file cuz I can
  file:
    path: "/tmp/tempfile.txt"
    state: touch
