---
- hosts: database
  tasks:
  
   

    - name: Create User Script
      command:  /tasks/oracle_user_nc.py/oracle_user_nc.py 
      register: sqlscript
    - debug:
        var: hostvars[inventory_hostname]
        tags: debug_info
      delegate_to: 127.0.0.1

    - name: Create user
      ansible.builtin.script: /Users/tonysawah/ansible/playbooks/orashell.sh "{{ sqlscript.stdout}}"
      with_items: "{{ groups['database'] }}"
      become_user: oracle
