---
- hosts: localhost
  tasks:
  - name: Output Survey Variables to JSON
    template:
      src: templates/input_user.j2
      dest: test_user_vars.json

  - name: Create a file
    file:
      path: "/tmp/buttekh.txt"
      state: touch
